# Form implementation generated from reading ui file 'file_name_gui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow2(object):
    def setupUi(self, MainWindow2):
        MainWindow2.setObjectName("MainWindow2")
        MainWindow2.resize(569, 113)
        MainWindow2.setMinimumSize(QtCore.QSize(569, 113))
        MainWindow2.setMaximumSize(QtCore.QSize(569, 113))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 9, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_fileNameEntry = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_fileNameEntry.setGeometry(QtCore.QRect(12, 19, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_fileNameEntry.setFont(font)
        self.lineEdit_fileNameEntry.setObjectName("lineEdit_fileNameEntry")
        self.Button_accept = QtWidgets.QPushButton(parent=self.groupBox)
        self.Button_accept.setGeometry(QtCore.QRect(434, 19, 101, 31))
        self.Button_accept.setMinimumSize(QtCore.QSize(101, 31))
        self.Button_accept.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Button_accept.setFont(font)
        self.Button_accept.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_accept.setObjectName("Button_accept")
        self.label_dotTxt = QtWidgets.QLabel(parent=self.groupBox)
        self.label_dotTxt.setGeometry(QtCore.QRect(390, 18, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dotTxt.setFont(font)
        self.label_dotTxt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dotTxt.setObjectName("label_dotTxt")
        self.line = QtWidgets.QFrame(parent=self.groupBox)
        self.line.setGeometry(QtCore.QRect(377, 19, 31, 31))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        MainWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 21))
        self.menubar.setObjectName("menubar")
        MainWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow2)
        self.statusbar.setObjectName("statusbar")
        MainWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow2)

    def retranslateUi(self, MainWindow2):
        _translate = QtCore.QCoreApplication.translate
        MainWindow2.setWindowTitle(_translate("MainWindow2", "FileNamer"))
        self.groupBox.setTitle(_translate("MainWindow2", "Enter file name:"))
        self.Button_accept.setText(_translate("MainWindow2", "Accept"))
        self.label_dotTxt.setText(_translate("MainWindow2", ".txt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow2 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow2()
    ui.setupUi(MainWindow2)
    MainWindow2.show()
    sys.exit(app.exec())
