# Form implementation generated from reading ui file 'file_finder_gui.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow5(object):
    def setupUi(self, MainWindow5):
        MainWindow5.setObjectName("MainWindow5")
        MainWindow5.resize(569, 113)
        MainWindow5.setMinimumSize(QtCore.QSize(569, 113))
        MainWindow5.setMaximumSize(QtCore.QSize(569, 113))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow5)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 551, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_fileFinderNameEntry = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_fileFinderNameEntry.setGeometry(QtCore.QRect(12, 19, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_fileFinderNameEntry.setFont(font)
        self.lineEdit_fileFinderNameEntry.setObjectName("lineEdit_fileFinderNameEntry")
        self.Button_openFile = QtWidgets.QPushButton(parent=self.groupBox)
        self.Button_openFile.setGeometry(QtCore.QRect(434, 19, 101, 31))
        self.Button_openFile.setMinimumSize(QtCore.QSize(101, 31))
        self.Button_openFile.setMaximumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Button_openFile.setFont(font)
        self.Button_openFile.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_openFile.setObjectName("Button_openFile")
        self.label_dotTxt = QtWidgets.QLabel(parent=self.groupBox)
        self.label_dotTxt.setGeometry(QtCore.QRect(390, 18, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_dotTxt.setFont(font)
        self.label_dotTxt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_dotTxt.setObjectName("label_dotTxt")
        self.line = QtWidgets.QFrame(parent=self.groupBox)
        self.line.setGeometry(QtCore.QRect(377, 19, 31, 31))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        MainWindow5.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 569, 21))
        self.menubar.setObjectName("menubar")
        MainWindow5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow5)
        self.statusbar.setObjectName("statusbar")
        MainWindow5.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow5)

    def retranslateUi(self, MainWindow5):
        _translate = QtCore.QCoreApplication.translate
        MainWindow5.setWindowTitle(_translate("MainWindow5", "FileFinder"))
        self.groupBox.setTitle(_translate("MainWindow5", "Enter name of file to open:"))
        self.Button_openFile.setText(_translate("MainWindow5", "Open"))
        self.label_dotTxt.setText(_translate("MainWindow5", ".txt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow5 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow5()
    ui.setupUi(MainWindow5)
    MainWindow5.show()
    sys.exit(app.exec())
